[env:uno]
platform = atmelavr
board = uno
framework = arduino

; Updated with the correct library registry names:
lib_deps =
    https://github.com/majicdesigns/md_parola
    https://github.com/majicdesigns/MD_MAX72XX
